language: node_js
cache:
  directories:
    - $HOME/.npm
notifications:
  email: false
node_js:
  - node
script:
  - npm run ci
after_success:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then npm run semantic-release; fi